# Filebeat inputs
filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /usr/share/filebeat/logs/app.log  
    fields:
      app_name: "EuropeanLawAdvisor"  

# Output to Elasticsearch
output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  username: ${ELASTICSEARCH_USERNAME}
  password: ${ELASTICSEARCH_PASSWORD}

setup.kibana:
  host: "localhost:5601"
  username: ${ELASTICSEARCH_USERNAME}
  password: ${KIBANA_PASSWORD}